### ISSUE TITLE
Would it be possible to provide release notes with every release

### ISSUE THREAD

**Issue by mymasse** [pivotal-cf/cf-rabbitmq-multitenant-broker-release#15]
The last 3 releases do not have release notes, would it be possible to add some. Helps in planning out the urgency or necessity to do an upgrade

**Comment by albertoleal** [comment]
Hi @mymasse,

We noticed that we have a few releases without "Releases Notes" and we want to fix them. We're improving our release process and that should address that in the future.

We're sorry about that.

Alberto and @mkuratczyk

**Comment by mymasse** [comment]
I see you guys added release notes to the existing releases, thanks.
