### ISSUE TITLE
User manual or quick start guide?

### ISSUE THREAD

**Issue by cwb124** [pivotal-cf/cf-rabbitmq-multitenant-broker-release#16]
Aside from basic install directions, could we get some additional documentation?  Once it's deployed via bosh....now what?  What is the broker expecting?  How can we use it?

**Comment by blgm** [comment]
Hi @cwb124, this repository has very little development happening any more.

In general, once it's deployed, you register the broker using the [broker registrar](https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release/tree/master/jobs/broker-registrar) errand

Are there some specific questions that you have?
