### ISSUE TITLE
The `rabbitmq-broker.rabbitmq.ssl` job property is not used

### ISSUE THREAD

**Issue by bgandon** [pivotal-cf/cf-rabbitmq-multitenant-broker-release#17]
Hi there,

Deploying RabbitMQ with TLS enabled, I saw that the `rabbitmq-broker.rabbitmq.ssl` property from the `rabbitmq-broker` job spec is actually never used by the job.

It would be nice from you to remove it so that people deploying this BOSH release don't get confused.
Thank you.

Best

**Comment by nodo** [comment]
Hi @bgandon,

We think that this property is used [here](https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release/blob/master/src/rabbitmq-broker/src/clojure/io/pivotal/pcf/rabbitmq/config.clj#L132).

In our template [here](https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release/blob/master/jobs/rabbitmq-broker/templates/broker_config.yml.erb#L10) we take all the properties of the `rabbitmq-broker` and pass them to the job. So, it's passed implicitly. 

Please, feel free to ping us if you have any doubts.

@mkuratczyk and @nodo
