### ISSUE TITLE
Add release to https://bosh.io/releases

### ISSUE THREAD

**Issue by rerooted** [pivotal-cf/cf-rabbitmq-multitenant-broker-release#2]
Hi,

Please can you add the built release to https://bosh.io/releases?  The 'cf-rabbitmq-release' is already there, so it seems like this should also be made available.

thanks

Rob

**Comment by albertoleal** [comment]
Hi @rerooted, we've opened a PR [1] to make sure that this release will be available on bosh.io. It should be available soon.

[1] https://github.com/bosh-io/releases/pull/18
