### ISSUE TITLE
Management ui connection problem when using dns_host

### ISSUE THREAD

**Issue by martjarvi** [pivotal-cf/cf-rabbitmq-multitenant-broker-release#39]
/instance_groups/name=rmq-broker/jobs/name=rabbitmq-service-broker/properties/rabbitmq-service-broker/rabbitmq/dns_host?

After setting dns_host as my external load balancer the broker tries to connect as http://my-external-lb:15672. I want to use https://my-external-lb instead. When not using dns_host and the management_domain is described correctly, it connects https:// correctly.

How to fix it?

**Comment by jccarte** [comment]
We are also having an issue related to this. It appears that the broker has http 15672 hardcoded: https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release/blob/master/src/rabbitmq-service-broker/main.go#L42

**Comment by thomasmitchell** [comment]
also having a problem with http being hardcoded in the broker

**Comment by coro** [comment]
Hello folks, apologies for the delay. This issue should be fixed in the next release of this repo, which will be 80.0.0.
